[package]
name = "spectre-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {workspace = true}
zip = {workspace = true}
reqwest = {workspace = true}
thiserror = {workspace = true}
spectre = {path = "../spectre"}
clap = {version = "4.5.37",features = ["derive"]}
home = {workspace = true}

[[bin]]
name = "spectre-cli"
path = "src/main.rs"