name: CI
env:
  CARGO_TERM_COLOR: always
on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('**/Cargo.lock')}}
      - name: Build all crates
        run: cargo build --release
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest]
    runs-on: ${{matrix.os}}
    env:
      SPECTRE_PORT: 2000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('**/Cargo.lock')}}
      - uses: taiki-e/install-action@nextest
      - name: Download chrome
        run: cargo run --release --bin spectre-cli download chrome
      - name: Run tests
        run: cargo nextest run --no-fail-fast
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    env:
      SPECTRE_PORT: 2000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('**/Cargo.lock')}}
      - name: Cargo fmt
        run: cargo fmt --check
  clippy:
    name: Linting
    runs-on: ubuntu-latest
    env:
      SPECTRE_PORT: 2000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('**/Cargo.lock')}}
      - name: Clippy
        run: cargo clippy -- -D warnings