name: Windows x86_64
on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build all crates
        run: cargo build --release

  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v2
        with: 
          deno-version: 'v2.x'
