name: Windows x86_64
on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('**/Cargo.lock')}}

      - name: Build all crates
        run: cargo build --release

  test:
    name: Test
    runs-on: windows-latest
    env:
      SPECTRE_PORT: 2000
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('**/Cargo.lock')}}

      - name: Build utils
        run: cargo build -p spectre-utils --release

      - name: Download chrome
        run: target/release/spectre-utils.exe download chrome
      
      - name: Run tests
        run: cargo test --no-fail-fast